src/Entity/QOptions.php
<?php

namespace App\Entity;

use App\Repository\QOptionsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QOptionsRepository::class)
 */
class QOptions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $decription;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_answer;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="qOptions")
     */
    private $question;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDecription(): ?string
    {
        return $this->decription;
    }

    public function setDecription(string $decription): self
    {
        $this->decription = $decription;

        return $this;
    }

    public function getIsAnswer(): ?bool
    {
        return $this->is_answer;
    }

    public function setIsAnswer(bool $is_answer): self
    {
        $this->is_answer = $is_answer;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }
}

src/Form/QOptionsType.php
<?php

namespace App\Form;

use App\Entity\QOptions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QOptionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('decription')
            ->add('is_answer')
            ->add('question')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => QOptions::class,
        ]);
    }
}

src/Controller/QOptionsController.php
<?php

namespace App\Controller;

use App\Entity\QOptions;
use App\Form\QOptionsType;
use App\Repository\QOptionsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/q/options")
 */
class QOptionsController extends AbstractController
{
    /**
     * @Route("/", name="q_options_index", methods={"GET"})
     */
    public function index(QOptionsRepository $qOptionsRepository): Response
    {
        return $this->render('q_options/index.html.twig', [
            'q_options' => $qOptionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="q_options_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $qOption = new QOptions();
        $form = $this->createForm(QOptionsType::class, $qOption);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($qOption);
            $entityManager->flush();

            return $this->redirectToRoute('q_options_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('q_options/new.html.twig', [
            'q_option' => $qOption,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="q_options_show", methods={"GET"})
     */
    public function show(QOptions $qOption): Response
    {
        return $this->render('q_options/show.html.twig', [
            'q_option' => $qOption,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="q_options_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, QOptions $qOption, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(QOptionsType::class, $qOption);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('q_options_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('q_options/edit.html.twig', [
            'q_option' => $qOption,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="q_options_delete", methods={"POST"})
     */
    public function delete(Request $request, QOptions $qOption, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$qOption->getId(), $request->request->get('_token'))) {
            $entityManager->remove($qOption);
            $entityManager->flush();
        }

        return $this->redirectToRoute('q_options_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/q_options/_delete_form.html.twig
<form method="post" action="{{ path('q_options_delete', {'id': q_option.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ q_option.id) }}">
    <button class="btn">Delete</button>
</form>

templates/q_options/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/q_options/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit QOptions{% endblock %}

{% block body %}
    <h1>Edit QOptions</h1>

    {{ include('q_options/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('q_options_index') }}">back to list</a>

    {{ include('q_options/_delete_form.html.twig') }}
{% endblock %}

templates/q_options/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}QOptions index{% endblock %}

{% block body %}
    <h1>QOptions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Decription</th>
                <th>Is_answer</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for q_option in q_options %}
            <tr>
                <td>{{ q_option.id }}</td>
                <td>{{ q_option.decription }}</td>
                <td>{{ q_option.isAnswer ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('q_options_show', {'id': q_option.id}) }}">show</a>
                    <a href="{{ path('q_options_edit', {'id': q_option.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('q_options_new') }}">Create new</a>
{% endblock %}

templates/q_options/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New QOptions{% endblock %}

{% block body %}
    <h1>Create new QOptions</h1>

    {{ include('q_options/_form.html.twig') }}

    <a href="{{ path('q_options_index') }}">back to list</a>
{% endblock %}

templates/q_options/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}QOptions{% endblock %}

{% block body %}
    <h1>QOptions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ q_option.id }}</td>
            </tr>
            <tr>
                <th>Decription</th>
                <td>{{ q_option.decription }}</td>
            </tr>
            <tr>
                <th>Is_answer</th>
                <td>{{ q_option.isAnswer ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('q_options_index') }}">back to list</a>

    <a href="{{ path('q_options_edit', {'id': q_option.id}) }}">edit</a>

    {{ include('q_options/_delete_form.html.twig') }}
{% endblock %}